/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppOeeRouteImport } from './routes/_app.oee'
import { Route as AppImportarProducaoRouteImport } from './routes/_app.importar-producao'
import { Route as AppImportarOeeRouteImport } from './routes/_app.importar-oee'
import { Route as AppImportarRouteImport } from './routes/_app.importar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppOeeRoute = AppOeeRouteImport.update({
  id: '/oee',
  path: '/oee',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarProducaoRoute = AppImportarProducaoRouteImport.update({
  id: '/importar-producao',
  path: '/importar-producao',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarOeeRoute = AppImportarOeeRouteImport.update({
  id: '/importar-oee',
  path: '/importar-oee',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/importar': typeof AppImportarRoute
  '/importar-oee': typeof AppImportarOeeRoute
  '/importar-producao': typeof AppImportarProducaoRoute
  '/oee': typeof AppOeeRoute
  '/producao': typeof AppProducaoRoute
}
export interface FileRoutesByTo {
  '/importar': typeof AppImportarRoute
  '/importar-oee': typeof AppImportarOeeRoute
  '/importar-producao': typeof AppImportarProducaoRoute
  '/oee': typeof AppOeeRoute
  '/producao': typeof AppProducaoRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/importar': typeof AppImportarRoute
  '/_app/importar-oee': typeof AppImportarOeeRoute
  '/_app/importar-producao': typeof AppImportarProducaoRoute
  '/_app/oee': typeof AppOeeRoute
  '/_app/producao': typeof AppProducaoRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/importar'
    | '/importar-oee'
    | '/importar-producao'
    | '/oee'
    | '/producao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/importar'
    | '/importar-oee'
    | '/importar-producao'
    | '/oee'
    | '/producao'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/importar'
    | '/_app/importar-oee'
    | '/_app/importar-producao'
    | '/_app/oee'
    | '/_app/producao'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oee': {
      id: '/_app/oee'
      path: '/oee'
      fullPath: '/oee'
      preLoaderRoute: typeof AppOeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-producao': {
      id: '/_app/importar-producao'
      path: '/importar-producao'
      fullPath: '/importar-producao'
      preLoaderRoute: typeof AppImportarProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-oee': {
      id: '/_app/importar-oee'
      path: '/importar-oee'
      fullPath: '/importar-oee'
      preLoaderRoute: typeof AppImportarOeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar': {
      id: '/_app/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportarRoute: typeof AppImportarRoute
  AppImportarOeeRoute: typeof AppImportarOeeRoute
  AppImportarProducaoRoute: typeof AppImportarProducaoRoute
  AppOeeRoute: typeof AppOeeRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportarRoute: AppImportarRoute,
  AppImportarOeeRoute: AppImportarOeeRoute,
  AppImportarProducaoRoute: AppImportarProducaoRoute,
  AppOeeRoute: AppOeeRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
