/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPuncionadeiraRouteImport } from './routes/_app.puncionadeira'
import { Route as AppProgramacaoRouteImport } from './routes/_app.programacao'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppOeeRouteImport } from './routes/_app.oee'
import { Route as AppImportarProducaoRouteImport } from './routes/_app.importar-producao'
import { Route as AppImportarOeeRouteImport } from './routes/_app.importar-oee'
import { Route as AppImportarRouteImport } from './routes/_app.importar'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPuncionadeiraRoute = AppPuncionadeiraRouteImport.update({
  id: '/puncionadeira',
  path: '/puncionadeira',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoRoute = AppProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppOeeRoute = AppOeeRouteImport.update({
  id: '/oee',
  path: '/oee',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarProducaoRoute = AppImportarProducaoRouteImport.update({
  id: '/importar-producao',
  path: '/importar-producao',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarOeeRoute = AppImportarOeeRouteImport.update({
  id: '/importar-oee',
  path: '/importar-oee',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof AppImportarRoute
  '/importar-oee': typeof AppImportarOeeRoute
  '/importar-producao': typeof AppImportarProducaoRoute
  '/oee': typeof AppOeeRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/programacao': typeof AppProgramacaoRoute
  '/puncionadeira': typeof AppPuncionadeiraRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/importar': typeof AppImportarRoute
  '/importar-oee': typeof AppImportarOeeRoute
  '/importar-producao': typeof AppImportarProducaoRoute
  '/oee': typeof AppOeeRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/programacao': typeof AppProgramacaoRoute
  '/puncionadeira': typeof AppPuncionadeiraRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/importar': typeof AppImportarRoute
  '/_app/importar-oee': typeof AppImportarOeeRoute
  '/_app/importar-producao': typeof AppImportarProducaoRoute
  '/_app/oee': typeof AppOeeRoute
  '/_app/producao': typeof AppProducaoRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/programacao': typeof AppProgramacaoRoute
  '/_app/puncionadeira': typeof AppPuncionadeiraRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/importar'
    | '/importar-oee'
    | '/importar-producao'
    | '/oee'
    | '/producao'
    | '/produtos'
    | '/programacao'
    | '/puncionadeira'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/importar'
    | '/importar-oee'
    | '/importar-producao'
    | '/oee'
    | '/producao'
    | '/produtos'
    | '/programacao'
    | '/puncionadeira'
    | '/'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/importar'
    | '/_app/importar-oee'
    | '/_app/importar-producao'
    | '/_app/oee'
    | '/_app/producao'
    | '/_app/produtos'
    | '/_app/programacao'
    | '/_app/puncionadeira'
    | '/_app/'
    | '/_app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/puncionadeira': {
      id: '/_app/puncionadeira'
      path: '/puncionadeira'
      fullPath: '/puncionadeira'
      preLoaderRoute: typeof AppPuncionadeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao': {
      id: '/_app/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof AppProgramacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oee': {
      id: '/_app/oee'
      path: '/oee'
      fullPath: '/oee'
      preLoaderRoute: typeof AppOeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-producao': {
      id: '/_app/importar-producao'
      path: '/importar-producao'
      fullPath: '/importar-producao'
      preLoaderRoute: typeof AppImportarProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-oee': {
      id: '/_app/importar-oee'
      path: '/importar-oee'
      fullPath: '/importar-oee'
      preLoaderRoute: typeof AppImportarOeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar': {
      id: '/_app/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportarRoute: typeof AppImportarRoute
  AppImportarOeeRoute: typeof AppImportarOeeRoute
  AppImportarProducaoRoute: typeof AppImportarProducaoRoute
  AppOeeRoute: typeof AppOeeRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppProgramacaoRoute: typeof AppProgramacaoRoute
  AppPuncionadeiraRoute: typeof AppPuncionadeiraRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportarRoute: AppImportarRoute,
  AppImportarOeeRoute: AppImportarOeeRoute,
  AppImportarProducaoRoute: AppImportarProducaoRoute,
  AppOeeRoute: AppOeeRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppProgramacaoRoute: AppProgramacaoRoute,
  AppPuncionadeiraRoute: AppPuncionadeiraRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
