/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPuncionadeiraRouteImport } from './routes/_app.puncionadeira'
import { Route as AppProgramacaoRouteImport } from './routes/_app.programacao'
import { Route as AppPainelTvRouteImport } from './routes/_app.painel-tv'
import { Route as AppDobraRouteImport } from './routes/_app.dobra'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPuncionadeiraRoute = AppPuncionadeiraRouteImport.update({
  id: '/puncionadeira',
  path: '/puncionadeira',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoRoute = AppProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelTvRoute = AppPainelTvRouteImport.update({
  id: '/painel-tv',
  path: '/painel-tv',
  getParentRoute: () => AppRoute,
} as any)
const AppDobraRoute = AppDobraRouteImport.update({
  id: '/dobra',
  path: '/dobra',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/dobra': typeof AppDobraRoute
  '/painel-tv': typeof AppPainelTvRoute
  '/programacao': typeof AppProgramacaoRoute
  '/puncionadeira': typeof AppPuncionadeiraRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dobra': typeof AppDobraRoute
  '/painel-tv': typeof AppPainelTvRoute
  '/programacao': typeof AppProgramacaoRoute
  '/puncionadeira': typeof AppPuncionadeiraRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dobra': typeof AppDobraRoute
  '/_app/painel-tv': typeof AppPainelTvRoute
  '/_app/programacao': typeof AppProgramacaoRoute
  '/_app/puncionadeira': typeof AppPuncionadeiraRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dobra'
    | '/painel-tv'
    | '/programacao'
    | '/puncionadeira'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dobra'
    | '/painel-tv'
    | '/programacao'
    | '/puncionadeira'
    | '/'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/dobra'
    | '/_app/painel-tv'
    | '/_app/programacao'
    | '/_app/puncionadeira'
    | '/_app/'
    | '/_app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/puncionadeira': {
      id: '/_app/puncionadeira'
      path: '/puncionadeira'
      fullPath: '/puncionadeira'
      preLoaderRoute: typeof AppPuncionadeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao': {
      id: '/_app/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof AppProgramacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel-tv': {
      id: '/_app/painel-tv'
      path: '/painel-tv'
      fullPath: '/painel-tv'
      preLoaderRoute: typeof AppPainelTvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dobra': {
      id: '/_app/dobra'
      path: '/dobra'
      fullPath: '/dobra'
      preLoaderRoute: typeof AppDobraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDobraRoute: typeof AppDobraRoute
  AppPainelTvRoute: typeof AppPainelTvRoute
  AppProgramacaoRoute: typeof AppProgramacaoRoute
  AppPuncionadeiraRoute: typeof AppPuncionadeiraRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDobraRoute: AppDobraRoute,
  AppPainelTvRoute: AppPainelTvRoute,
  AppProgramacaoRoute: AppProgramacaoRoute,
  AppPuncionadeiraRoute: AppPuncionadeiraRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
